# Generated by Django 6.0.3 on 2026-05-06 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_document_analysis_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('property', 'Property'), ('legal', 'Legal'), ('financial', 'Financial'), ('inspection', 'Inspection'), ('tax', 'Tax')], default='property', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('required_fields', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SellerDocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='not_submitted', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='seller_documents/%Y/%m/%d/')),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_submissions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.propertydocumenttemplate')),
            ],
            options={
                'ordering': ['template__order', '-submitted_at'],
                'unique_together': {('seller', 'template')},
            },
        ),
    ]
